add git clone btn to projects explorer view
alefragnani/vscode-project-manager pull request #446
Opened 2020-12-22 04:38 UTC by ctf0

for quicker adding new projects instead of going to the scm panel to clone first.

2020-12-25 21:03 UTC, alefragnani requested changes

2020-12-25 21:03 UTC, alefragnani commented on package.json
> +				    	"when": "view =~ /(projectsExplorerVSCode|projectsExplorerGit|projectsExplorerSVN|projectsExplorerAny|projectsExplorerMercurial)/",
The `clone` command should be available only for the `projectsExplorerGit` view.

2020-12-25 22:07 UTC, ctf0 commented on package.json
> +				    	"when": "view =~ /(projectsExplorerVSCode|projectsExplorerGit|projectsExplorerSVN|projectsExplorerAny|projectsExplorerMercurial)/",
done

2020-12-29 00:19 UTC, alefragnani commented
Thanks for the update 👍 

I'm looking for an event that could be called _after the clone_ has been made. With that, the project list could be automatically refreshed.

2021-08-30 08:10 UTC, closed without merging